name = "mute-wave-6894"
pages_build_output_dir = "./dist"


[[d1_databases]]
binding = "DB" # available in your Worker on env.DB
database_name = "quotes"
database_id = "a4065acf-5f48-4d5a-acdf-edffa9ea86ff"
preview_database_id = "a4065acf-5f48-4d5a-acdf-edffa9ea86ff" # Required for Pages local development

# [[unsafe.bindings]]
# name = "LIMITER"
# type = "ratelimit"
# namespace_id = "1001"
# simple = { limit = 200, period = 60 }
